INSERT INTO users (name, age)
VALUES ('Margarita', 20),
        ('Mariya', 22),
        ('Sofya', 19),
        ('Ivan', 23),
        ('Roman', 30),
        ('Viktoriya', 28),
        ('Maryam', 22),
        ('Vladimir', 18),
        ('Alisa', 15),
        ('Emiliya', 33),
        ('Evgeniy', 25),
        ('Kseniya', 35),
        ('Yuliya', 17),
        ('Medina', 26),
        ('Mikhail', 28),
        ('Andrey', 21),
        ('Arina', 29),
        ('Aleksandra', 25),
        ('Anna', 31),
        ('Nikol', 16);